
SELECT DISTINCT
	IO.nID,
	IO.nSellingGroup,
	IO.nItemID1,
	IO.nItemID2,
	IO.nItemID3,
	IO.nItemID4,
	IO.nItemID5,
	IO.nItemID6,
	IO.nItemID7,
	IO.nItemID8,
	IO.nItemID9,
	IO.nItemID10,
	IO.nItemID11,
	IO.nItemID12,
	IO.nItemID13,
	IO.nItemID14,
	IO.nItemID15,
	IO.nItemID16,
	IO.nItemID17,
	IO.nItemID18,
	IO.nItemID19,
	IO.nItemID20,
	IO.nItemID21,
	IO.nItemID22,
	IO.nItemID23,
	IO.nItemID24
FROM
	{BASE_TABLE_NAME} AS IO   
ORDER BY `nID` ASC;

